vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/article
            upload_destination: '%kernel.project_dir%/public/images/article'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
